version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - restore_cache:
          keys:
          - deps-{{ checksum "build.gradle" }}-{{ .Environment.CACHE_VERSION }}

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: deps-{{ checksum "build.gradle" }}-{{ .Environment.CACHE_VERSION }}

      - run: gradle test
